#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      PATH="$(python -m site --user-base)/bin:$PATH"
      export PYTHON=python PIP=pip VENV=virtualenv
      ;;
  esac

  mkdir -p "$shome/vendor"
  git clone https://github.com/lyft/python-blessclient "$shome/vendor/blessclient" || true
  block compile virtualenv
  "$shome/vendor/virtualenv/bin/pip" install -e "$shome/vendor/blessclient"

  git clone https://github.com/Netflix/bless "$shome/vendor/bless"
  if cd "$shome/vendor/bless"; then
    git fetch
    git reset --hard
    git checkout 0.2.0
  fi
}

main "$@"
