#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Darwin)
      PATH="$(python -m site --user-base)/bin:$PATH"
      export PYTHON=python PIP=pip VENV=virtualenv
      ;;
    Linux)
      pkg ensure x11/py-Tk
      ;;
  esac

  mkdir -p "$shome/vendor"

  git clone https://github.com/Netflix/bless "$shome/vendor/bless"
  if cd "$shome/vendor/bless"; then
    git fetch
    git reset --hard
    git checkout master
    git reset --hard 0.2.0
    block compile virtualenv
    source vendor/virtualenv/bin/activate
    make develop 
    make test
  fi

  git clone https://github.com/lyft/python-blessclient "$shome/vendor/blessclient" || true
  if cd "$shome/vendor/blessclient"; then
    block compile virtualenv
    "$shome/vendor/bless/vendor/virtualenv/bin/pip" install -e .
  fi
}

main "$@"
