#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "$shome/vendor/virtualenv/bin/blessclient" ]]; then
    return 1
  fi

  if [[ ! -d "$shome/vendor/bless" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
