#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_blessclient="$BLESSCLIENT_VERSION"
  jq -n \
    --arg blessclient "$ver_blessclient" \
      '{blessclient: $blessclient}'
}

version "$@"
