#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_bless="$BLESS_VERSION"
  jq -n \
    --arg bless "$ver_bless" \
      '{bless: $bless}'
}

version "$@"
